### ISSUE TITLE
VM crashed while taking the screen shot with browser stack

### ISSUE THREAD

**Issue by thamizhkumarana** [saikrishna321/nakal_java#13]
Dear Sai,

Is there any way i can integrate the nakal-java with cloud devices like (browserstack, sauce lab).

This is the code block i have used:
new NakalExecutor().nakalExecutorNativeCompare("splashscreen");

Library version:
<version>fa8e3cc5f6</version>

Trying to take the screen shot on real device.

Whenever the nakal try to take the screenshot my VM getting crashed. 

Please find the below  error.
[INFO] Total time: 02:22 min
[INFO] Finished at: 2018-03-28T15:50:24+05:30
[INFO] Final Memory: 15M/178M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project selenium: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/mobile/Documents/regression/DeltaFrame/selenium && /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java -jar /Users/mobile/Documents/regression/DeltaFrame/selenium/target/surefire/surefirebooter517697220037686871.jar /Users/mobile/Documents/regression/DeltaFrame/selenium/target/surefire/surefire1991029350296579094tmp /Users/mobile/Documents/regression/DeltaFrame/selenium/target/surefire/surefire_08705246060925082180tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project selenium: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /Users/mobile/Documents/regression/DeltaFrame/selenium && /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/bin/java -jar /Users/mobile/Documents/regression/DeltaFrame/selenium/target/surefire/surefirebooter517697220037686871.jar /Users/mobile/Documents/regression/DeltaFrame/selenium/target/surefire/surefire1991029350296579094tmp /Users/mobile/Documents/regression/DeltaFrame/selenium/target/surefire/surefire_08705246060925082180tmp
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)

**Comment by thamizhkumarana** [comment]
Null pointer exception when i use below code.

new NakalExecutor().nakalExecutorWebCompare(driver,"splashscreen");

And i can see the directory created as 
ios/null/baseline_images

along with the below message:
BaseLine Image Directory is created!

**Comment by saikrishna321** [comment]
yes, it should work as your comparing the results in your local machine and all that you do with cloud services is run your tests. So technically it should work.

**Comment by saikrishna321** [comment]
@hiteshsh
